version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: false
  tslint:
    enabled: false
exclude_patterns:
  - ".github/"
  - "dist/"
  - "samples/"
  - "test/"
  - "utl/"
  - "**/node_modules/"
