version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - ".github/"
  - "dist/"
  - "samples/"
  - "test/"
  - "utl/"
  - "**/node_modules/"